services:
  to-do-postgres-database:
    image: postgres:latest
    restart: 'no'
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    container_name: to-do-postgres-database
    ports:
      - ${POSTGRES_HOST_CONTAINER}
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          'CMD-SHELL',
          'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -h localhost -p 5432',
        ]
      interval: 30s
      timeout: 10s
      retries: 5